name: 'ThotPatrol'
version: ${project.version}
description: 'Anti-Cheat add-on for Minecraft: Java Edition'
authors: [ 'Alerithe', 'Hexeption' ]
main: io.github.alerithe.thotpatrol.ThotPatrolPlugin
commands:
  thotpatrol:
    description: Main command for Thot Patrol